# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Money by Pounds
email: rich@rpfinancialplanning.com
description: Financial planning by Richard Pounds, CFP.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
sass:
  sass_dir: /assets/css
